let meta_data = [
    
    {
        "numero" : "2",
        "name" : "Cercle démocratique de Lausanne",
        "date": "01/01/1938",
        "event" : "Inauguration de la maison du Cercle démocratique à la Place de la Riponne. ", 
        "persons" : "Intervenant - Addor Jules-Henri <br>Intervenant - Béboux Eugène <br>Intervenant - Blanc Albert <br>Intervenant - Bosset Norbert <br>Intervenant - Chessex Louis <br>Intervenant - Cottier Henri <br>Intervenant - Fischer Ernest <br>Intervenant - Martinet Jules <br>Intervenant - Oyex César<br>Intervenant - Perret Paul<br>Intervenant - Pilet-Golaz Marcel<br>Intervenant - Porchet Ferdinand<br>Intervenant - Vallotton Henri",
        "data": "1 pellicule inversible16mm noir/blanc, 12 im/s, muet. Une copie de ce film, cotée K00432 (P006) est conservée au Ciné-photo Police et n'a pas été versée aux Archives.",
        "desc": "Arrivée des officiels en gare de Lausanne et fanfare: Henri Valloton (président du Conseil national en 1939), Georges Bridel, P. Rochat. Réception, tables fleuries. Flambeaux, le Casino de Montbenon de nuit. Drapeau 1843-1929. Entrée du cercle à Haldimand. (La place de la Riponne sans la Grenette. WC à l'angle Tunnel-Riponne)​. Arrivée du cortège, foule, fanfare. Vues devant les bâtiments du Musée Arlaud et de la Maison Pelet. Ferdinand Porchet, conseiller d'Etat; Henri Cottier. Le repas; Marcel Pilet-Golaz; Paul Perret, conseiller d'Etat de l'instruction publique; Jules-Henri Addor; Jules Martinet, sécrétaire du parti radical; César Oyex et Louis Chessex, entrepreneurs; P. Rochat parle; Norbert Bosset, conseiller d'Etat. Le repas du cercle; les dames du vestiaire. Les discours: Henri Cottier; Albert Blanc, préfet de Lausanne; Marcel Pilet-Golaz, vice-président du Conseil fédéral; Paul Perret, conseiller d'Etat; Ernest Fischer, conseiller d'Etat. On voit encore: Charles Gorgerat, Eugène Hirzel, conseiller national, Henri Genet, Arthur Prod'hom, Jean Peitrequin, Robert Bolomey, hommes de partis politiques lausannois, ainsi que MM. Aguet, Bosset, Tschumi. Le film se termine avec un bal, l'image d'un drapeau vaudois \"offert par les dames, 24 janvier 1903\", et le slogan << Liberté et Patrie >>.", 
        "author": "Cinéac Lausanne",
        
    },
    
    {
        "numero" : "3",
        "name" : "Inauguration patinoire Montchoisi",
        "date": "15/11/1938",
        "event" : "Lausanne a inauguré la patinoire de Monchoisi avec glace  artificielle. (Tribune de Lausanne 20.11.1938 -P5). ", 
        "persons" : "Intervenant - Addor Jules-Henri<br>Intervenant - Bridel Georges",
        "data": "Pellicule 16mm noir/blanc 18im/s muet. 26 mètres.",
        "desc": "Lausanne a inauguré la patinoire de Monchoisi avec glace artificielle. En présence des officiels: Jules Addor, syndic de Lausanne, Georges Bridel, directeur de Police; la presse; les patineurs en action, patinage en groupes; vues des gradins provisoirement installés.", 
        "author": "Cinéac Lausanne",
    },
    {
        "numero" : "5",
        "name" : "Ecole Vinet",
        "date": "27/05/1939",
        "event" : "Commémoration du centenaire de l'Ecole Vinet par les anciens élèves, devant la statue .", 
        "persons" : "",
        "data": "16 mm - Pellicule filmique et muet.",
        "desc": "Monument Alexandre Vinet, fanfare et cortège des anciens et des actuels de l'année 1939. Arrivée devant le monument à Montbenon. Les fleurs du souvenir au pied du monument; discours de Mlle Paschaud, professeur à l’école des visages, un chœur assure l'animation; foule dense.", 
        "author": "Cinéac Lausanne",
   },
   {
        "numero" : "6",
        "name" : "Remise du drapeau",
        "date": "01/01/1939",
        "event" : "Remise du drapeau sur l'esplanade de Montbenon.", 
        "persons" : "Intervenant - Major Paul Brunner<br>Intervenant - Albert Von der Aa<br>Intervenant - Préfêt Blanc",
        "data" : "16 mm - Pellicule filmique et muet.",
        "desc" : "Sur l'esplanade, remise du drapeau. Fanfare sur les escaliers devant le Palais de Justice de Montbenon. Discours: Major Paul Brunner, commandant de la police lausannoise, Albert Von der Aa; Michel Jaccard, rédacteur à la Nouvelle Revue de Lausanne. Préfêt Blanc.",
        "author" : "Cinéac Lausanne",
   },
   {
        "numero" : "7",
        "name" : "Concours de boules",
        "date": "01/01/1939",
        "event" : "Concours international de boules ferrées, le Challenge d'Ouchy.", 
        "persons" : "",
        "data" : "16 mm - Pellicule filmique et muet",
        "desc" : "Concours international de boules ferrées, organisé par le Bellerives-Ouch​y-Club à Bellerive", 
        "author" : "Cinéac Lausanne",
    },
    {
        "numero" : "8",
        "name" : "Sumner Welles",
        "date": "01/03/1940",
        "event" : "Benjamin Sumner Welles, sous-secrétaire d'Etat américain, de passage à Lausanne.", 
        "persons" : "Intervenant - Welles Summer",
        "data" : "16 mm - Pellicule filmique et muet",
        "desc" : "Après être arrivé à la gare, Summer Welles se promène au bord du lac à Ouchy en bonne compagnie; un garde du corps le suit, la main enfouie dans sa poche. Balade jusqu'à la tour Haldimand; vue du port, le lac, les cygnes. Manifestation à l'avenue Benjamin-Consta​nt; des gens accrochent un drapeau belge ou hollandais; manchette de journal : \"La Belgique et la Hollande résistent et font appel aux alliés\". La police arrive pour disperser les manifestants et enlever le drapeau.", 
        "author" : "Cinéac Lausanne",
    },
    {
        "numero" : "9",
        "name" : "Union instrumentale",
        "date": "14/04/1940",
        "event" : "Concert de l'Union instrumentale, à l'occasion de la fête cantonale vaudoise.", 
        "persons" : "",
        "data" : "16 mm - Pellicule filmique et muet",
        "desc" : "14 avril ! Fête vaudoise !Le cortège. La fanfare quitte l'hôpital cantonal et défile à la rue du Pont, s'installe pour un concert devant une foule dense à la Palud. Les musiciens et leur chef; nombreux plans détaillant instruments et costumes. L'Union Instrumentale a donné un concert à l'Hôpital Cantonal, puis défile dans les rues de la ville. Devant l'Hôtel de Ville, elle a donné son aubade traditionnelle!​", 
        "author" : "Cinéac Lausanne",
    },
    {
        "numero" : "11",
        "name" : "Course d'aviron",
        "date": "01/01/1940",
        "event" : "Course d'aviron à Ouchy.", 
        "persons" : "",
        "data" : "16 mm - Pellicule filmique et muet",
        "desc" : "Depuis un bateau, vues des courses de quatre avec barreur, ski (flotteur), etc. Les rives du lac, les officiels, la remise des prix.", 
        "author" : "Cinéac Lausanne",
    },
    {
        "numero" : "12",
        "name" : "650e Confédération",
        "date": "29/05/1941",
        "event" : "Commémoration du 650e anniversaire de la Confédération à la Place de la Riponne par les écoliers lausannois.", 
        "persons" : "Intervenant -  Georges Bridel",
        "data" : "16 mm - Pellicule filmique et muet",
        "desc" : "Les écoliers lausannois commémorent le 650e anniversaire de la Confédération. Palais de Rumine; la place. Les élèves des écoles en cortège sur la Riponne. Discours. On reconnaît Georges Bridel, directeur de Police. Drapeaux; défilé vu depuis les escaliers de Rumine. Foule nombreuse.", 
        "author" : "Cinéac Lausanne",
    },
    {
        "numero" : "13",
        "name" : "Amis gymnastes à Béthusy",
        "date": "30/05/1941",
        "event" : "Les Amis-gymnastes de notre ville ont disputé un concours interne de pupille.", 
        "persons" : "",
        "data" : "16 mm - Pellicule filmique et muet",
        "desc" : "Terrain des Amis-gymnastes à Béthusy. Exercices divers sur le gazon; on voit assez bien les bâtiments aux alentours. Saut à la perche. Cheval d'arçon; exercices au sol; le public, saut en hauteur; les officiels. Joueurs de quilles.", 
        "author" : "Cinéac Lausanne",
    },
     {
        "numero" : "14",
        "name" : "Revues au Théâtre municipal",
        "date": "01/01/1941",
        "event" : "Diverses revues au Théâtre municipal.", 
        "persons" : "Intervenant - Badès Jean<br>Intervenant - Béranger Jacques<br>Intervenant - Deprez Georges<br>Intervenant - Mauchair Jean<br>Intervenant - Thoos Jean",
        "data" : "16 mm - Pellicule filmique et muet",
        "desc" : "Revues entre 1939 et 1941.<br>1941: Extraits de la revue \"Garde-à-vous fisc\" plans de mannequins, de danse et quelques scénettes; \"Voici quelques scènes surprises par la caméra de Cinéac...\" \"Vive nous\" de Maurice Hayward 1939. <br>Vue extérieure du Théâtre municipal; affiches; Jacques Béranger, directeur, dans son bureau; Jean Mauchair, metteur en scène; Deprez, musique; Jean Thoos, pour les décors. M. Foujane du Casino de Paris; R.Buguet et Jean Badès, des Folies Bergères; Lilian Gills (Miss Paris 1938).<br>Nombreux costumes. \"Viens z'y voir!\" avec Hélène Regelly, Philippe Soguel, Tamara Beck. 1940: un comédien costumé en soldat prend des notes sur un calepin et raconte... <br>Jacques Béranger avec une dame. \"Le grand ballet de Tamara Beck\"<br>Essais de costumes avec la femme de Jacques Béranger; Tamara Beck; ballets guerriers... Albert Itten; Scène de la revue.",
        "author" : "Cinéac Lausanne",
    },
    {
        "numero" : "15",
        "name" : "Assermentation du Grand Conseil",
        "date": "01/01/1941",
        "event" : "Défilé du Grand Conseil sur la place du Château.", 
        "persons":"",
        "data" : "16 mm - Pellicule filmique et muet",
        "desc" : "Place du Château, sous la neige. En tenue d'apparat, les gendarmes présentent les armes. Salut au drapeau, fanfare devant les députés du Grand Conseil au complet sur les marches. Le cortège devant l'obélisque (non réparé). Paul Chaudet au micro. ", 
        "author" : "Charles Brönimann",
    },
    {
        "numero" : "18",
        "name" : "Assermentation du Grand Conseil",
        "date": "01/01/1945",
        "event" : "Assermentation du Grand Conseil le 24 avril 1945.", 
        "persons" : "Intervenant - Paul Chaudet",
        "data" : "16 mm - Pellicule filmique et muet",
        "desc" : "Assermentation du Grand Conseil: sur la place du Château; gendarmes; députés en habit d'apparat; Conseil d'Etat avec Paul Chaudet", 
        "author" : "Cinéac Lausanne",
    },
    {
        "numero" : "19",
        "name" : "L'armistice - la joie lausannoise ",
        "date": "01/01/1945",
        "event" : "La joie dans les rues de Lausanne après l'annonce de la capitulation de l'Allemagne.", 
        "persons" : "Intervenant - Gabriel Despland<br>Intervenant - Jules-Henri Addor",
        "data" : "16 mm - Pellicule filmique et muet",
        "desc" : "Vendeurs de journaux avec en gros titre: \"L'Allemagne capitule\". Cortège de gens qui descendent l'avenue Benjamin-Consta​nt au pas de danse. Défilé en contre-jour devant la poste de Saint-François. Vallorbe: premier train venant de France. Officiels et cheminots se saluent à la gare. On reconaît Gabriel Despland, conseiller d'Etat; Jules-Henri Addor, syndic de Lausanne.", 
        "author" : "Cinéac Lausanne",
    },
    {
        "numero" : "20",
        "name" : "Fête du bois",
        "date": "01/01/1946",
        "event" : "Cortège de la Fête du bois en 1946.", 
        "persons" : "Intervenant - Georges Bridel<br>Intervenant - Albert von der Aa",
        "data" : "16 mm - Pellicule filmique et muet",
        "desc" : "Cortège de la Fête du bois au débouché du Grand-Chêne sur la place Saint-François. On reconnaît les municipaux Georges Bridel et Albert von der Aa. La banque fédérale existe encore. Agents de police avec anciens uniformes.", 
        "author" : "Cinéac Lausanne",
    },
    {
        "numero" : "21",
        "name" : "Grand Conseil",
        "date": "12/4/1949",
        "event" : "Assermentation du Grand Conseil sur la Place du Château.", "persons" : "Intervenant - Rudolphe Rubattel<br>Intervenant - Lucien Rubattel<br>Intervenant - Gabriel Despland<br>Intervenant - Edmond Jaquet<br>Intervenant - Arthur Maret<br>Intervenant - Pierre Oguey",
        "data" : "16 mm - Pellicule filmique et muet",
        "desc" : "Place du Château; le Conseil d'Etat sur les escaliers. Défilé de la gendarmerie; prise du drapeau; cortège en direction de la Cathédrale; entrée dans la Cathédrale; les députés en habits d'apparat avec les queues d'hirondelle. Vus: Rudolphe Rubattel, conseiller fédéral, Lucien Rubattel (colonel); Gabriel Despland, Edmond Jaquet, Arthur Maret, Pierre Oguey, tous conseillers d'Etat.", 
        "author" : "Cinéac Lausanne",
    },
    {
        "numero" : "23",
        "name" : "Fête fédérale de gymnastique",
        "date": "16/07/1951",
        "event" : "Cortège des gymnastes à la Place St-François lors de la fête fédérale de Gymnastique à Lausanne le 14 juillet 1951.",
        "persons" : "",
        "data" : "1 Pellicule 16mm inversible couleur 12 im/s et muet",
        "desc" : " Défilé des gymnastes sur la place Saint-François devant un public nombreux et bigarré; sections des gymnastes précédées par des groupes de musiciens et par des porteurs de bannières. Prises de vue réalisées depuis un point fixe, à savoir le magasin de photo Robert Schnell, sis à la place Saint-François N° 4. Avec le bâtiment des Postes en vue.", 
        "author" : "Cinéac Lausanne",
    },
    {
        "numero" : "27",
        "name" : "Anniversaire de l'indépendance vaudoise",
        "date": "14/04/1953",
        "event" : "Commémoration de l'indépendance vaudoise.", 
        "persons" : "Intervenant - Max Petitpierre<br>Intervenant - Dr Roger Benoit<br>Intervenant - Lucien Rubattel<br>Intervenant - Aimé Delay<br>Intervenant - Kobelt<br>Intervenant - major Cornaz<br>Intervenant - major Davel",
        "data" : "16 mm - Pellicule filmique et muet",
        "desc" : "Conseil d'Etat à la Riponne, devant le musée Arlaud; Max Petitpierre. Cully: défilé devant l'obélisque érigé en mémoire du major Davel. Morges. Place de la Riponne (devant le bâtiment de l'Etat): prise du drapeau. Dr Roger Benoit, directeur des Abattoirs de la ville de Lausanne; Aimé Delay; Lucien Rubattel; Kobelt. Montée à la Cathédrale par la gendarmerie; major Cornaz. Entrée des députés dans la Cathédrale. Vues depuis la terrasse en face du Café Vaudois; Pont Bessières; avenue Benjamin-Consta​nt; le cortège (chevaux, chars, enfants). Place Saint-François (sous la pluie); avenue Benjamin-Constant: chars divers.", 
        "author" : "Cinéac Lausanne",
    },
    {
        "numero" : "29",
        "name" : "Élections communales",
        "date": "18/11/1953",
        "event" : "Elections communales à Lausanne.", 
        "persons" : "",
        "data" : "16 mm - Pellicule filmique et muet",
        "desc" : "Renouvellement des autorités communales lausannoises pour la législature 1954-57. Vue depuis Montbenon sur la ville et la Cathédrale, ainsi que quelques plans nocturnes. Tour Bel-Air. Place de la Palud, slogans; affiches électorales. Les journaux. La votation; il y a foule! Vues intérieures des bureaux. Résultats dans les journaux. La place de la Palud.", 
        "author" : "Cinéac Lausanne",
    },
    {
        "numero" : "30",
        "name" : "Avec les chanteurs vaudois",
        "date": "01/01/1938",
        "event" : "Avec les chanteurs vaudois à Lausanne. Retour sur la fête cantonale de chant à Lausanne.", 
        "persons" : "Intervenant - Guisan Henri",
        "data" : "Pellicule 16mm 24 im/s nb et muet",
        "desc" : "Avec les chanteurs vaudois: défilé à Montbenon puis à la place Saint-François; drapeaux, chanteurs, fanfares, police. Place de la Palud: discours (?); Carlo Hemmerling dirige les choeurs à Beaulieu: repas, discours entre autres du Général Henri Guisan.", 
        "author" : "Cinéac Lausanne",
    },
    {
        "numero" : "35",
        "name" : "Course des garçons de café",
        "date": "01/01/1955",
        "event" : "Septième critérium intervilles organisé par la Fraternenelle des garçons de café de Lausanne.", 
        "persons" : "",
        "data" : "16 mm - Pellicule filmique et muet",
        "desc" : "Septième critérium intervilles organisé par la Fraternelle des garçons de café de Lausanne. La course des hommes et des dames à travers le centre-ville. Vues principalement prises sur la place de la Riponne.", 
        "author" : "Cinéac Lausanne",
    },
    {
        "numero" : "37",
        "name" : "Fête du bois",
        "date": "01/01/1959",
        "event" : "Reflet de la fête du bois en 1959. ", 
        "persons" : "",
        "data" : "16 mm - Pellicule filmique et muet",
        "desc" : "Fanfare de la police municipale à la place Saint-François, rue Pépinet. Sauvabelin; carrousels; les enfants: des pas de danse; place de la Riponne; Sauvabelin: les biches. Beaucoup de isages d'enfants; un portrait attendri. Pancarte <br>\"Objets perdus; enfants égarés\" (Jeux: tir à l'arc sur des \"mores\": on tire sur des effigies d'enfants noirs). On joue ensemble, et pour les plus grands ça se termine en se contant fleurette...", 
        "author" : "Ernest Ansorge",
    },
    {
        "numero" : "40",
        "name" : "Centre équestre de Vidy",
        "date": "01/01/1961",
        "event" : "Le manège.", 
        "persons" : "Intervenant - Georges Gruaz",
        "data" : "16 mm - Pellicule filmique et muet",
        "desc" : "Au manège, figures et parcours divers des cavaliers. Georges Gruaz, promoteur du centre équestre de Vidy, a obtenu de la commune de Lausanne, le 11 mai 1956, un droit de superficie pour construire un centre équestre, à Vidy. Celui-ci, à cause de l'Exposition Nationale, fut déplacé en 1962 au Chalet-à-Gobet.", 
        "author" : "Cinéac Lausanne",
    },
    {
        "numero" : "42",
        "name" : "Expo 64",
        "date": "01/01/1964",
        "event" : "Série de courts reportages sur l'Exposition nationale de 1964 à Lausanne. ", 
        "persons" : "Intervenant - Chaudet Paul<br>Intervenant - Chevallaz Georges-André<br>Intervenant - Deppen Robert<br>Intervenant - Despland Gabriel<br>Intervenant - Graber Pierre<br>Intervenant - Gros Marcel<br>Intervenant - Guisan Henri<br>Intervenant - Guisan Louis",
        "data" : "Films 16mm versés par Ernest Ansorge (P333) et muet",
        "desc" : "Les journalistes s'affairent; des ours tournent en rond dans leur fosse; vues depuis le train aérien; divers cortèges provenant du centre-ville en direction de l'entrée nord de l'Exposition par l'avenue de Provence. Inauguration: Gabriel Despland, Georges-André Chevallaz. La gare, départ du cortège avec les conseillers fédéraux: Paul Chaudet, Hans-Peter Tschudi, Friedrich Wahlen, Hans Schaffner, Ludwig von Moos, Roger Bonvin, Willy Spühler, et le général Henri Guisan. La Voie Suisse; vues sur l'Exposition; plan général. Discours devant le pavillon de l'armée: Edouard Henry, P. Grandjean, et diverses délégations étrangères. Stade de Vidy: l'armée alignée; Paul Chaudet à la tribune. Entrée du cortège à la Vallée de la Jeunesse; avenue de Tivoli; etc.. Esplanade: Pierre Graber, Paul Chaudet, Louis Guisan, Jean-Jacques Bolens, Carlo Hemmerling. Discours: Louis Guisan. Cortège sur Tivoli \"Le Valais\". Vus: Pierre Vuillemin, Robert Deppen, Louis Guisan, Heinz Geiger, Monseigneur Séverin de Haller, abbé de St-Maurice, Marcel Gros, conseiller d'Etat, Louis Dupont-Lachenal​, chanoine de Saint-Maurice. Discours: Gabriel Despland. Cortège \"Berne\". Avenue de Provence. Vues: Philippe Etter, Friedrich Wahlen. Discours: Gabriel Despland.", 
        "author" : "Ernest Ansorge",
    },
    {
        "numero" : "43",
        "name" : "Match de football",
        "date": "01/15/1964",
        "event" : "Match de football SATUS (Fédération de gymnastique et de sport) Suisse-France lors de l'Exposition nationale 1964. ", 
        "persons" : "",
        "data" : "Ce film a été fait avec les chutes du film réalisé pour la Journée d'inauguration par le Cartel syndical vaudois. Son de mauvaise qualité.",
        "desc" : "Match organisé le 1er mai dans le cadre de l'Exposition nationale 1964 de Lausanne par la SATUS, Fédération de gymnastique et de sport. La SATUS fut fondée en 1874.", 
        "author" : "Octave Heger",
    },
    {
        "numero" : "44",
        "name" : "Cortège du 1er mai",
        "date": "01/03/1964",
        "event" : "Cortège du 1er mai lors de l'Exposition nationale de Lausanne.", 
        "persons" : "",
        "data" : "16 mm - Pellicule filmique et langue audio française",
        "desc" : "Vues en haut du carrefour de Georgette. Fanfares, drapeaux, syndicalistes toutes tendances confondues. 16'000 participants selon le commentaire. \"On n'avait vu ça à Lausanne! Un cortège du 1er mai de 13'000 participants [sic] et vingt corps de musique, défilant pendant plus d'une heure dans les rues bien dégagées de la ville. Aucun slogan, car ils étaient interdits. Probablement, l'attrait de l'Exposition a été pour une bonne part dans cette affluence\" (Extrait de: Images et évenements vaudois, par Marion Mendelzwaig-Dro​z, Genève 1990, p. 209).", 
        "author" : "Cinéac Lausanne",
    },
    {
        "numero" : "45",
        "name" : "Fête des écoles enfantines",
        "date": "09/07/1967",
        "event" : "La fête des écoles enfantines de Lausanne en 1967. ", 
        "persons" : "Intervenant - Deppen Robert",
        "data" : "16 mm - Pellicule filmique et langue audio française",
        "desc" : "Avenue William-Fraisse​: défilé des écoles enfantines en direction de la place de Milan. André Piller, conseiller communal socialiste; Robert Deppen, directeur de police.", 
        "author" : "Octave Heger",
    },
    {
        "numero" : "49",
        "name" : "Exposition Pully",
        "date": "31/08/1967",
        "event" : "Exposition Toulouse Lautrec à Pully.", 
        "persons" : "",
        "data" : "16 mm - Pellicule filmique et muet",
        "desc" : "Vernissage; vues des tableaux.", 
        "author" : "Cinéac Lausanne",
    },
    {
        "numero" : "50",
        "name" : "Fête de la tour de l'Ale",
        "date": "02/09/1967",
        "event" : "Fête organisée par le regroupement des commerçants de la rue de l’Ale à l’occasion des 700 ans de l’érection de la Tour.", 
        "persons" : "Intervenant - Chevallaz Georges-André<br>Intervenant - Dessemontet Olivier<br>Intervenant - Urfer Albert",
        "data" : "1 pellicule 16mm couleur 24 im/s et muet",
        "desc" : "Affiche (filmée en guise de titre); fête organisée par le regroupement des commerçants de la rue de l’Ale à l’occasion des 700 ans de l’érection de la Tour; plans fixes sur la tour; Georges-André Chevallaz; Albert Urfer; Olivier Dessemontet, directeur des Archives cantonales vaudoises; défilé de la fanfare \"L'Instrumental​e\" dans la rue de l'Ale; pique-nique populaire. ", 
        "author" : "Cinéac Lausanne",
    },
    {
        "numero" : "54",
        "name" : "Forains",
        "date": "01/01/1968",
        "event" : "Vues des manèges sur la place de la Riponne. ", 
        "persons" : "",
        "data" : "16 mm - Pellicule filmique et langue audio française",
        "desc" : "Vues des manèges à la Place de la Riponne.", 
        "author" : "Octave Heger",
    },
    {
        "numero" : "55",
        "name" : "Carnaval des enfants",
        "date": "17/02/1968",
        "event" : "Carnaval des enfants à la patinoire de Montchoisi.", 
        "persons" : "",
        "data" : "16 mm - Pellicule filmique et muet",
        "desc" : "25ème carnaval. Déguisements et patinage \"artistique\" des enfants à la patinoire de Monchoisi.", 
        "author" : "Cinéac Lausanne",
    },
    {
        "numero" : "56",
        "name" : "Martin Luther King",
        "date": "16/04/1968",
        "event" : "Manifestation pacifique dans les rues de Lausanne après l'assassinat de Martin Luther King.", 
        "persons" : "",
        "data" : "16 mm - Pellicule filmique et muet",
        "desc" : "Place St-François. Manifestation à la suite de la mort de Martin Luther King. Défilé, banderoles. Montée rue de Bourg, puis rue du Pont, présence d'une nombreuse foule! Sur la place de la Riponne. Escaliers du Valentin, la foule gravit les marches et entre dans l'église.", 
        "author" : "Cinéac Lausanne",
    },
    {
        "numero" : "57",
        "name" : "Sherlock Holmes",
        "date": "28/04/1968",
        "event" : "Sherlock Holmes et sa suite accueillis à Ouchy.", 
        "persons" : "Intervenant - Chevallaz Georges-André<br>Intervenant - Despland Gabriel",
        "data" : "16 mm - Pellicule filmique et langue audio française",
        "desc" : "Personnes en costumes d’époque au sortir d’un bateau sur un débarcadère à Ouchy. Accueil par Georges-André Chevallaz, syndic, et Gabriel Despland, président de l’office national suisse du tourisme. ", 
        "author" : "Octave Heger",
    },
    {
        "numero" : "59",
        "name" : "Ecolier romand le plus rapide",
        "date": "04/05/1968",
        "event" : "Course des écoliers à Vidy.", 
        "persons" : "",
        "data" : "16 mm - Pellicule filmique et muet",
        "desc" : "Journée de sélection lausannoise pour la compétition de l'écolier romand le plus rapide. A Vidy. Courses diverses, inscription, les enfants au rapport; Dave James, double chaampion suisse de course..", 
        "author" : "Cinéac Lausanne",
    },
    {
        "numero" : "60",
        "name" : "Vin d'Epesses à la Palud",
        "date": "11/05/1968",
        "event" : "", 
        "persons" : "",
        "data" : "16 mm - Pellicule filmique et langue audio française",
        "desc" : "Dégustation sur la place de la Palud du vin d'Epesse. Fêtes et gens qui se pressent pour déguster divers crus, dont le Dorin 67. Projections du 17 au 23 mai 1968 au CINEAC.", 
        "author" : "Octave Heger",
    },
    {
        "numero" : "61",
        "name" : "Gymkana",
        "date": "12/05/1968",
        "event" : "Premier gymkana romand des routiers suisses.", 
        "persons" : "",
        "data" : "16 mm - Pellicule filmique et langue audio française",
        "desc" : "Gymkhana: Une grande publicité pour les camions Mercedes, avant de voir plusieurs exercices; mouvement de bascule; arrêt de précision. Projections du 17 au 23 mai 1968 au CINEAC.", 
        "author" : "Octave Heger",
    },
    {
        "numero" : "62",
        "name" : "Fête des enseignes",
        "date": "18/05/1968",
        "event" : "Fête des enseignes à la rue Cité Derrière.", 
        "persons" : "",
        "data" : "16 mm - Pellicule filmique et langue audio française",
        "desc" : "Vues de Vues de plusieurs anciennes enseignes, cortège et musique. Lecture d'un texte par Gil Pidoux. Les enseignes sont dévoilées. cortège avec les grenadiers.", 
        "author" : "Octave Heger",
    },
    {
        "numero" : "63",
        "name" : "Revue des pompiers de pully",
        "date": "01/01/1968",
        "event" : "Images de la revue des sapeurs pompiers de Pully.", 
        "persons" : "",
        "data" : "16 mm - Pellicule filmique et muet",
        "desc" : "Revue et execices annuels des sapeurs-pompier​s de Pully. Défilé avec la fanfare municipale, Le commandant major Pierre Gamboni, le syndic Louis Thaler.", 
        "author" : "Cinéac Lausanne",
    },
    {
        "numero" : "64",
        "name" : "Solidarité estudiantine",
        "date": "01/01/1968",
        "event" : "Manifestation \"Solidarité étudiante\" en mai 68 à la place de la Gare de Lausanne. ", 
        "persons" : "",
        "data" : "1 pellicule 16mm inversible couleur 24 im/s et langue audio française",
        "desc" : "Manifestation Solidarité étudiante en mai 68 à la place de la Gare de Lausanne. Banderoles: Droits syndicaux aux étudiants, Non à la répression, Solidarité, Non à l'uni technocratique, oui à l'uni critique, 6 pourcent d'ouvriers, 14 poucent de femmes dans les uni suisses, le pourcent le plus bas d'Europe, Non à l'uni outil du capitalisme, Non à l'immobilisme confiant, prenons nos responsabilités​, Turin, Berlin, Paris et Dorigny (?) même combat, Contrôle étudiant. Manifestants assis sur les escaliers qui mènent au cinéma Georges V; environ 200 personnes, discours. M. Bony enregistre pour la Radio ? Projections du 17 au 23 mai 1968 au CINEAC.", 
        "author" : "Octave Heger",
    },
    {
        "numero" : "65",
        "name" : "Promotions scolaires",
        "date": "29/03/1969",
        "event" : "Promotions scolaires en 1969 à Pully.", 
        "persons" : "",
        "data" : "16 mm - Pellicule filmique et muet",
        "desc" : "Cortège, salut aux autorités. Aula: remise des  diplômes.", 
        "author" : "Octave Heger",
    },
    {
        "numero" : "67",
        "name" : "Revue du Corps de Police",
        "date": "01/01/1938",
        "event" : "La revue annuelle du Corps de Police lausannois sur la place de Montbenon.", 
        "persons" : "Intervenant - Addor Jules-Henri<br>Intervenant - Brunner Paul",
        "data" : "1 pellicule 16mm inversible noir/blanc 16 im/s et muet",
        "desc" : "La revue annuelle du Corps de Police lausannois sur la place de Montbenon enneigée avec le casino en arrière-plan; inspection par la municipalité, ainsi que le major Paul Brunner. Escaliers du Palais de Justice; \"remise des galons aux agents nouvellement promus\"; \"défilé devant les autorités\"; Jules-Henri Addor, syndic.", 
        "author" : "Cinéac Lausanne",
    },
    {
        "numero" : "68",
        "name" : "Assermentation de la DAP",
        "date": "03/09/1939",
        "event" : "Sous les ordres du Major Paul Brunner, la Défense Aérienne Passive (DAP) a prêté serment au drapeau à Montbenon, devant le préfet de Lausanne.", 
        "persons" : "Intervenant - Blanc Albert<br>Intervenant - Bonnard Louis-Henri<br>Intervenant - Dumuid (Adjudant)<br>Intervenant - Favez (Major)",
        "data" : "1 pellicule 16mm 18 im/s noir/blanc muet, 40m.",
        "desc" : "Sous les ordres du Major Paul Brunner, la Défense Aérienne Passive (DAP) a prêté serment au drapeau à Montbenon, devant Albert Blanc, le préfet de Lausanne; on aperçoit le Colonel Louis-Henri Bonnard, Commandant de la place, ainsi que MM. Favez, Dummiel; escaliers devant le Palais de Justice; kiosque à musique; des femmes incorporées; discours devant la troupe rassemblée; défilé sur l'avenue Jules-Gonin.", 
        "author" : "Cinéac Lausanne",
    },
    {
        "numero" : "69",
        "name" : "Revue de la Police",
        "date": "01/01/1940",
        "event" : "La revue annuelle de la Police de Lausanne.", 
        "persons" : "Intervenant - Addor Jules-Henri<br>Intervenant - Brunner Paul",
        "data" : "1 pellicule 16mm noir/blanc 18 im/s, muet, 33 mètres.",
        "desc" : "La revue annuelle du Corps de Police lausannois sur la place de Montbenon enneigée avec le Casino en arrière-plan; inspection par la Municipalité, ainsi que le Major Paul Brunner; escaliers du Palais de Justice; \"Remise des galons aux agents nouvellement promus\"; \"Défilé devant les autorités\"; Jules-Henri Addor, syndic.", 
        "author" : "Cinéac Lausanne",
    },
    {
        "numero" : "70",
        "name" : "Défilé de l'infanterie motorisée 2",
        "date": "01/05/1964",
        "event" : "", 
        "persons" : "Intervenant - Dénéréaz Eugène<br>Intervenant - Gafner Raymond",
        "data" : "Pellicule 16mm couleur 24 im/s et muet",
        "desc" : "Le colonel Raymond Gafner présente ses troupes pour le défilé de son régiment à Saint-François, au divisionnaire Eugène Dénéréaz. Vues de l'entrée du Cinéac (où l'on projette \"Voyage féérique autour du monde\"); camions, motos militaires sur le Grand-Pont (vue de la Cathédrale); avenue du Théatre (bâtiments de la Banque Cantonale Vaudoise et des Postes en réfection).", 
        "author" : "René Ofmann",
    },
    {
        "numero" : "73",
        "name" : "Hommage statue Guisan",
        "date": "01/01/1967",
        "event" : "Grenadiers fribourgeois devant la statue du Général Guisan.", 
        "persons" : "Intervenant - Guisan Henri",
        "data" : "16 mm - Pellicule filmique et langue audio française",
        "desc" : "Les Grenadiers fribourgeois devant le monument du général Henri-Guisan à Ouchy. Major L. Bulliard.", 
        "author" : "Octave Heger",
    },
    {
        "numero" : "75",
        "name" : "Monument Guisan",
        "date": "27/05/1967",
        "event" : "Inauguration du monument à la mémoire du Général Henri Guisan à Ouchy.", 
        "persons" : "Intervenant - Celio Nello<br>Intervenant - Chevallaz Georges-André<br>Intervenant - Guisan Henri",
        "data" : "16 mm - Pellicule filmique et langue audio française",
        "desc" : "A Ouchy, devant une foule considérable, le dévoilement de la statue équestre. Discours: Georges-André Chevallaz et Nello Celio. Officiels, officiers, huissiers, fanfare, etc. Puis défilé devant les officiels; drapeaux, fantassins, chars, etc. Beau soleil. La Télévision Suisse Romande est présente. Amorce de fin Kodak.", 
        "author" : "Octave Heger",
    },
    {
        "numero" : "77",
        "name" : "80 ans du Général Guisan",
        "date": "21/10/1954",
        "event" : "Hommage rendu au Général Guisan à l'occasion de son 80e anniversaire.", 
        "persons" : "Intervenant - Guisan Henri",
        "data" : "16 mm - Pellicule filmique et muet",
        "desc" : "Place de la Riponne. Les officiels sur les escaliers devant le palais de Rumine. Le Général en uniforme salue la fanfare militaire et passe en revue les troupes. Les officiers. Salutations et poignées de mains. On voit: Le général Henri Guisan, Paul Chaudet, Edouard Henry, Arthur Maret, J. Grandjean; Paul Nerfin, directeur de la Banque Cantonale Vaudoise. Au Château. Officiels sur les marches, salutations; gendarmes; gymnastes. On voit: Alfred Oulevay, Lucien Rubattel, Louis Guisan, Paul Chaudet, Arthur Maret, Pierre Oguey, Charles Sollberger, tous conseillers d'Etat et Aimé Delay, municipal lausannois des Services industriels.", 
        "author" : "Cinéac Lausanne",
    },
    {
        "numero" : "82",
        "name" : "Manifestations patriotiques ",
        "date": "01/01/1940",
        "event" : "Manifestations patriotiques, Fête du 1er août.", 
        "persons" : "",
        "data" : "16 mm - Pellicule filmique et muet",
        "desc" : "Vue générale depuis le Signal de Sauvabelin. Le château Saint-Maire. Réveil à 5h du matin par une fanfare juchée sur un camion; mise en place du drapeau sur la flèche de la Cathédrale. Camion garé sur la place de la Riponne (bâtiment de Rumine avec immense drapeau suisse). La flèche de la Cathédrale avec deux personnes qui l'ont escaladée! Monument aux morts à Montbenon (derrière le Palais de Justice); Georges Bridel, municipal; police; fanfare, armée; salut du drapeau; Prière dite par le Capitaine Ferrari; Albert Blanc, préfet de Lausanne; soldats infirmières. Devant le Casino, la fanfare; Ferdinand Porchet, conseiller d'Etat; cortège: départ sous les ordres de René Huber depuis la place de la Riponne. Fanfare et cortège devant le Café Vaudois; cavaliers; officiels; Jean Peitrequin, directeur des travaux; Arthur Maret, conseiller municipal; gendarmes; infirmière; infirmiers vaudois casqués; éclaireurs; fanfare; feux de joie; gymnaste.", 
        "author" : "Cinéac Lausanne",
    },
    {
        "numero" : "83",
        "name" : "Bataillon 125",
        "date": "01/01/1939",
        "event" : "Le bataillon 125 défile dans les rues de Lausanne avant d'être démobilisé.", 
        "persons" : "Intervenant - Rubattel Lucien",
        "data" : "16 mm - Pellicule filmique et muet",
        "desc" : "Défilé en fanfare place Saint-François sous les yeux du lieutenant colonel Lucien Rubattel, commandant du bataillon. Soldats; un camion privé avec mitrailleuse; la foule. A Beaulieu, devant les halles en bois, les armes, les soldats se relaxent et chantent. Rassemblement avant le départ pour Montbenon. Arrivée à Montbenon; la fanfare; prise de drapeau; la bannière entre dans le Palais de justice; soldats au garde à vous (devant le kiosque). Retour à Beaulieu, tout est fini; soldats en vadrouille, rires; la troupe alignée sur l'esplanade de Beaulieu. Dernier défilé (avenue Henri-Jomini ?), arrivée à Beaulieu; pause; les officiers cassent la croûte. Soirée de compagnie avec fragments de spectacle: comique troupier, chants et de nombreux visages filmés lors de cette réunion pittoresque.", 
        "author" : "Cinéac Lausanne",
    }
];
